CREATE DATABASE montink;
USE montink;

CREATE TABLE cupons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    validade TIMESTAMP DEFAULT NULL,
    valorMinimo DECIMAL (10,2) DEFAULT 0,
    valorFrete DECIMAL (10,2) DEFAULT 0,
    ativo TINYINT NOT NULL DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE produtos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR (500) NOT NULL,
    ativo TINYINT(2) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE itens_produtos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idProduto INT NOT NULL,
    preco DECIMAL (10,2) NOT NULL DEFAULT 0,
    estoque INT DEFAULT 0,
    cor VARCHAR (200) NOT NULL,
    tamanho VARCHAR (200) NOT NULL,
    referencia VARCHAR (200) NOT NULL,
    ativo TINYINT NOT NULL DEFAULT '1',
    FOREIGN KEY (idProduto) REFERENCES produtos(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE pedidos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    valorPedido DECIMAL(10,2) DEFAULT 0,
    valorFrete DECIMAL (10,2) DEFAULT 0,
    dataPedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(500) DEFAULT NULL,
    idCupom INT NOT NULL,
    FOREIGN KEY (idCupom) REFERENCES cupons(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE itens_pedidos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idPedido INT NOT NULL,
    quantidade INT DEFAULT 0,
    idItem INT NOT NULL,
    FOREIGN KEY (idPedido) REFERENCES pedidos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idItem) REFERENCES itens_produtos(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;